#!/bin/sh

start() {
	mode="664"
	group="staff"
   device="scull"
   module="scull"
	
	/sbin/insmod /lib/modules/6.1.44/extra/scull.ko
   major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

   rm -f /dev/${device}[0-3]
   mknod /dev/${device}0 c $major 0
   mknod /dev/${device}1 c $major 1
   mknod /dev/${device}2 c $major 2
   mknod /dev/${device}3 c $major 3
   ln -sf ${device}0 /dev/${device}
   chgrp $group /dev/${device}[0-3] 
   chmod $mode  /dev/${device}[0-3]

   rm -f /dev/${device}pipe[0-3]
   mknod /dev/${device}pipe0 c $major 4
   mknod /dev/${device}pipe1 c $major 5
   mknod /dev/${device}pipe2 c $major 6
   mknod /dev/${device}pipe3 c $major 7
   ln -sf ${device}pipe0 /dev/${device}pipe
   chgrp $group /dev/${device}pipe[0-3] 
   chmod $mode  /dev/${device}pipe[0-3]

   rm -f /dev/${device}single
   mknod /dev/${device}single  c $major 8
   chgrp $group /dev/${device}single
   chmod $mode  /dev/${device}single

   rm -f /dev/${device}uid
   mknod /dev/${device}uid   c $major 9
   chgrp $group /dev/${device}uid
   chmod $mode  /dev/${device}uid

   rm -f /dev/${device}wuid
   mknod /dev/${device}wuid  c $major 10
   chgrp $group /dev/${device}wuid
   chmod $mode  /dev/${device}wuid

   rm -f /dev/${device}priv
   mknod /dev/${device}priv  c $major 11
   chgrp $group /dev/${device}priv
   chmod $mode  /dev/${device}priv

   /sbin/insmod /lib/modules/6.1.44/extra/faulty.ko
   module="faulty"
   major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
   rm -f /dev/$module
   mknod /dev/$module c "$major" 0 
   chgrp $group /dev/faulty
   chmod $mode /dev/faulty

   /sbin/insmod /lib/modules/6.1.44/extra/hello.ko
   module="hello"
   mknod /dev/$module c 268 0 
   chgrp $group /dev/$module
   chmod $mode /dev/$module


}
   
stop() {
   module="scull"
   device="scull"

   # invoke rmmod with all arguments we got
   rmmod $module $* || exit 1

   # Remove stale nodes

   rm -f /dev/${device} /dev/${device}[0-3] 
   rm -f /dev/${device}priv
   rm -f /dev/${device}pipe /dev/${device}pipe[0-3]
   rm -f /dev/${device}single
   rm -f /dev/${device}uid
   rm -f /dev/${device}wuid

   module="faulty"
   /sbin/rmmod $module
   rm -f /dev/$module

   module="hello"
   /sbin/rmmod $module
   rm -f /dev/$module

}

   
case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    *)
       echo "Usage: $0 {start|stop}"
esac
   
exit 0 
